clickhouse:
  image:
    repository: yandex/clickhouse-server
    tag: 21.8
    pullPolicy: IfNotPresent

  config:
    hot:
      min_part_size: 5000000000
      method: zstd
    cold:
      min_part_size: 10000000000
      method: zstd

  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 20Gi

  service:
    type: ClusterIP
    port: 9000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi