apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . | nindent 9}}
spec:
  type: {{.Values.clickhouse.service.type }}
  ports:
    - port: {{.Values.clickhouse.service.port }}
      targetPort: clickhouse
      protocol: TCP
      name: clickhouse
  selector:
    app.kubernetes.io/name: {{ include "clickhouse.fullname" . | nindent 12}}
    app.kubernetes.io/instance: {{.Release.Name }}